### ISSUE TITLE
Issue when building the examples

### ISSUE THREAD

**Issue by LarissaAuberger** [IBM-Blockchain/learn-chaincode#35]
When executing go build ./ for the start and finish code, I see the following message:
cannot use new(SimpleChaincode) (type *SimpleChaincode) as type shim.Chaincode in argument to shim.Start:
*SimpleChaincode does not implement shim.Chaincode (wrong type for Init method)
have Init(*Shim.ChaincodeStub, string, []string)([]byte, error)
want Init(shim.ChaincodeStubInterface, string, []string) ([]byte, error)

**Comment by LarissaAuberger** [comment]
Example seems to be out of date. Fixed by changing shim.ChaincodeStub to shim.ChaincodeStubInterface.

**Comment by dshuffma-ibm** [comment]
well sort of, welcome to our on-going saga of shiminterface changes.  

the issue you hit is very well known at this point, but its still going to catch people off guard until we improve the situation. this pr would fix it for Hyperledger networks using 0.6.x, though it would break networks with 0.5.x https://github.com/IBM-Blockchain/learn-chaincode/pull/20 . 

looks like our current plan is to hold tight until we get bluemix + everyone else upgraded to 0.6.x. though adding version management would be the preferred solution.
